sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet --trace
env:
  global:
    secure: "abmRzZHmkgzlw60fNfR0iRtTLg3cGa9ZzrCbZ9Ty3uG7eQRvCH5uLyKd9GaCYVw1EsbenYQXgdMQ/nP+/tBNYcA066RHl2/2myK5TJW46NtJHVTGzBDfLg9qxI1dkbx5WAMueDQgNPC/q9zgPwAYuHFZ71PdDxnaccG/OoQQ5a1yzKQ85br8REyQreKqta8EG8F/RQbz/8TRXNuNML+DCglLpfz1aS+Dl0euGcxFktQhbPz6TXApuv6D/io+o5lEMxRf3VhvuXVLIMNig3UdtphFeMcsg7yFjYUFOuS6uuseDQgGSORYON9624eSEETZVqp2KMZioJrVSB3icWcnwM1xLBHrVplJLM21J6DnlaVek/YEue4wmkhKllVbshBw2C1D4LQ9IQ3xJRNEl8n3QzokaC1kt8ZPI2v7Y547uxurlr4hB9MvpvffCozOIe3jhXCDS2NEHDmH41h6hki4IOHZwJvMyKT2Zmu8I3urNQHlpI0XbFUBdMNRpWkRC19BCQ0H+zJaj4nZYOiB9SgesuR4CHX3BtWZ2ylqWypNSJQzy5eAjxj7TPQ5Zf5QjSeGhAn8rIFjVn87+2yHqweG15PGhHxTTmus3ZTcYh9redp0iX3wh8LbgrobGn5szajvaiTRgT1nuiSssV1uTM6P1orLQVvZGgu/SyFPAxcKySw="
  only:
  - master